"use strict";
exports.__esModule = true;
var fs = require("file-system");
var _1 = require("../lib/");
var schemaText = fs.readFileSync("./example.avsc", "UTF8");
var schema = JSON.parse(schemaText);
var typeNames = [];
console.log("test: " + typeNames);
var avroToTypeScriptResult = _1.avroToTypeScript(schema, typeNames);
console.log(avroToTypeScriptResult.tsInterface);
